# Generated by Django 4.1.2 on 2022-10-28 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apiuser_liked_posts_post_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
