# Generated by Django 4.1.2 on 2022-10-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='bookmarked_posts',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='api.post'),
        ),
    ]
