# Generated by Django 4.1.2 on 2022-11-04 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_apiuser_bookmarked_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now=True)),
                ('replied_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.post')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
