# Generated by Django 4.1.2 on 2022-11-27 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='reply',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_replies', to='api.apiuser'),
            preserve_default=False,
        ),
    ]
